### ISSUE TITLE
How to support tsx file?

### ISSUE THREAD

**Issue by xcatliu** [azu/parcel-typescript-example#2]
I tried to use tsx but got an error:

```
Server running at http://localhost:1234
        // 是否允许推�...' in E:\work\buluo\src\node_modules\@tencent\breadui\site\index.tsx
    at module.exports (E:\work\buluo\src\node_modules\@tencent\breadui\node_modules\parse-json\index.js:26:19)
    at Object.load (E:\work\buluo\src\node_modules\@tencent\breadui\node_modules\parcel-bundler\src\utils\config.js:36:12)
    at <anonymous>
```

**Comment by xcatliu** [comment]
Problem solved after I upgraded to the latest version (v1.2.0) of parcel-bundler
